version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: dotnet --info